projects: {spectrum: /home/luc/projects/website-spectrum-59-q3-2022, tta: /home/luc/projects/tta-onepager, x-back: /home/luc/projects/x-ingredient-api-v2, x-front: /home/luc/projects/x-ingredient-company-website-new}
