projects: {tta-onepager: /home/luc/projects/tta-onepager, spectrum: /home/luc/projects/website-spectrum-59-q3-2022, x-backend: /home/luc/projects/x-ingredient-api-v2, x-frontend: /home/luc/projects/x-ingredient-company-website-new}
