projects:
  biking:
    dir: /home/lucdewit/projects/biking-activity
    url: null
  cca:
    dir: /home/lucdewit/projects/cca
    url: null
  ccvm:
    dir: /home/lucdewit/projects/ccvm
    url: null
  scripts:
    dir: /home/lucdewit/scripts
    url: null
  tta:
    dir: /home/lucdewit/projects/tta-onepager
    url: null
gitusers:
  Luc:
    fullname: Luc de Wit
    aliases:
      - Luc de Wit
      - luc.dewit
  Martijn:
    fullname: Martijn Engelkes
    aliases:
      - Martijn Engelkes
      - Martijn
weatherapi:
  api_key: 2989580c2d5235b00a77e8c45d25976c
  lat: 51.7006741
  lon: 5.3126206
